### ISSUE TITLE
Remove .tmp files

### ISSUE THREAD

**Issue by Syndrast** [Atlls/project_locroto#9]
The .tmp files introduced in commit fc5f9f6 are temporary artifacts generated by Godot on Windows, they should not be tracked by the version control system.

![Captura de pantalla 2024-10-23 084000](https://github.com/user-attachments/assets/55be6209-c7d5-42c3-9593-9d36dd846872)

@GerardoDiaz22

**Comment by GerardoDiaz22** [comment]
Done. Solved in commit [https://github.com/Atlls/project_locroto/commit/395eb534c55a61d18b65cca52613705e76ecc9d0](url).
